# -*- coding: utf-8 -*-
"""Fotograf og lisens for bildene som brukes i «Dette finnes i området».
Hentet fra Wikimedia Commons (extmetadata: Artist, LicenseShortName) 16.9.2026.
Nøklene bruker understrek, slik Commons selv normaliserer filnavn."""

NYE_KREDITT = {
    # --- Kreta
    'Preveli_Palm_Beach_03.JPG': ('Uoaei1', 'CC BY-SA 4.0'),
    'Preveli_Palm_Beach_Panorama_02.JPG': ('Uoaei1', 'CC BY-SA 4.0'),
    'ELA_-_Long_sandy_beach_at_Elafonisi,_Crete,_Greece,_2015.jpg': ('Josep M. Gracia', 'CC BY-SA 4.0'),
    'Balos_1.jpg': ('Olaf Tausch', 'CC BY-SA 3.0'),
    'Damnoni_Beach_(1018849199).jpg': ('Wolfgang Staudt', 'CC BY 2.0'),
    'Falassarna_-_Kréta_-_panoramio_(4).jpg': ('Pavel Špindler', 'CC BY 3.0'),
    'Kreta_-_Kournas-See.jpg': ('Taxiarchos228', 'Free Art License'),
    'Gorge_of_Samaria_Biosphere_Reserve,_Crete,_Greece_(2).jpg': ('Sebastian Mierzwa', 'CC BY-SA 4.0'),
    'Kreta_(GR),_Amnatos,_Kloster_Arkadi_--_2023_--_8553.jpg': ('Dietmar Rabich', 'CC BY-SA 4.0'),
    'Kreta_(GR),_Rethymno,_Fortezza_--_2023_--_8236.jpg': ('Dietmar Rabich', 'CC BY-SA 4.0'),
    'Kreta_(GR),_Rethymno,_Fortezza_--_2023_--_8239.jpg': ('Dietmar Rabich', 'CC BY-SA 4.0'),
    'Kreta_(GR),_Rethymno,_Alter_Hafen,_Leuchtturm_--_2023_--_8328.jpg': ('Dietmar Rabich', 'CC BY-SA 4.0'),
    'Kreta_(GR),_Rethymno,_Venezianischer_Brunnen_Rimondi_--_2023_--_8762.jpg': ('Dietmar Rabich', 'CC BY-SA 4.0'),
    'Kreta_(GR),_Chania,_Alter_Hafen,_Leuchtturm_--_2023_--_8527.jpg': ('Dietmar Rabich', 'CC BY-SA 4.0'),
    'Harbor,_Venetian_shipyards_and_Lighthouse_in_Chania._Crete,_Greece.jpg': ('Ввласенко', 'CC BY-SA 3.0'),
    'Bull_leaping_minoan_fresco_archmus_Heraklion.jpg': ('Jebulon', 'CC0'),
    'Knossos_R03.jpg': ('Marc Ryckaert (MJJR)', 'CC BY 3.0'),
    'Gyro_03.jpg': ('JELYL', 'CC BY-SA 4.0'),
    'Bougatsa_(with_vannila_custard)_-_IL.FOXO_2026-02-13.jpg': ('Andy Li', 'CC0'),
    # --- Costa Blanca
    'Bosque_de_Sierra_Helada_con_vistas..jpg': ('leviatan89', 'CC BY-SA 3.0 es'),
    'Des_de_la_Serra_Gelada_cap_a_la_mar_-_panoramio.jpg': ('Alacanti1975', 'CC BY 3.0'),
    'Faro_de_Punta_Albir_03.jpg': ('Triplecaña', 'CC BY-SA 4.0'),
    "Playa_de_l'Albir.JPG": ('Kisueses', 'CC BY-SA 3.0 es'),
    'Playa_del_Racó_del_Albir.JPG': ('Jackrm', 'Public domain'),
    'Altea,_Spain_(26889065385).jpg': ('Brett Hodnett', 'CC BY-SA 2.0'),
    "Cúpula_d'Altea.jpg": ('Nikon63', 'CC BY-SA 4.0'),
    "Absis_i_cúpula,_església_de_la_mare_de_Déu_del_Consol_d'Altea.JPG": ('Joanbanjo', 'CC BY-SA 4.0'),
    'Guadalest,_Alicante,_España,_2023-01-21,_DD_11.jpg': ('Diego Delso', 'CC BY-SA 4.0'),
    'Castillo,_Guadalest,_Alicante,_España,_2023-01-21,_DD_27.jpg': ('Diego Delso', 'CC BY-SA 4.0'),
    'Vista_de_Alicante,_España,_2014-07-04,_DD_67-70_PAN.JPG': ('Diego Delso', 'CC BY-SA 3.0'),
    'Colorful_buildings_of_the_historical_La_Vila_Joiosa,_Alicante,_Spain,_2022_January.jpg': ('Ximonic (Simo Räsänen)', 'CC BY-SA 4.0'),
    "Aigua_i_roca_del_toll_Blau_de_les_fonts_de_l'Algar.jpg": ('Joanbanjo', 'CC BY-SA 4.0'),
    "El_toll_del_Baladre_de_les_fonts_de_l'Algar.jpg": ('Joanbanjo', 'CC BY-SA 4.0'),
    'La_grotte_de_canelobre_-_panoramio_(6).jpg': ('chisloup', 'CC BY 3.0'),
    'Tabarca_Island-Alicante_(Spain)_-_48502234451.jpg': ('Jose A.', 'CC BY 2.0'),
    'Playa_de_Levante,_Benidorm,_España,_2014-07-02,_DD_86.JPG': ('Diego Delso', 'CC BY-SA 3.0'),
    'Playa_de_Levante,_Benidorm,_España,_2014-07-02,_DD_33.JPG': ('Diego Delso', 'CC BY-SA 3.0'),
    'Isla_de_Benidorm,_España,_2014-07-02,_DD_58.JPG': ('Diego Delso', 'CC BY-SA 3.0'),
    'Magnus_Colossus_tematización.JPG': ('Vicreate', 'CC BY-SA 3.0'),
    # --- Split
    'Bacvice_Beach_in_Split,_Croatia_(48608741537).jpg': ('dronepicr', 'CC BY 2.0'),
    'Picigolwiki.jpg': ('Dedinski89', 'CC BY-SA 4.0'),
    'Kasjuni_Beach_-_Split_-_Croatia_2023_05.jpg': ('Elbert Hampton', 'CC0'),
    'J32_653_Bol,_Zlatni_Rat,_Hvar.jpg': ('Falk2', 'CC BY-SA 4.0'),
    'Brela_BW_2024-10-04_15-43-18.jpg': ('Berthold Werner', 'CC BY-SA 4.0'),
    'Podstrana_Split_20210710_090931.jpg': ('Romanm', 'CC BY-SA 4.0'),
    "Aerial_view_of_Diocletian's_Palace_in_Split,_Croatia_(48608247353).jpg": ('dronepicr', 'CC BY 2.0'),
    "Peristyle_of_Diocletian's_Palace,_Split_(11908116224).jpg": ('Following Hadrian', 'CC BY-SA 2.0'),
    'Bell_Tower_Of_Cathedral_of_Saint_Domnius_-_Split.jpg': ('Sumitsurai', 'CC BY-SA 4.0'),
    'Split_Cathedral_Bell_Tower_From_The_Vestibule_-_Split.jpg': ('Sumitsurai', 'CC BY-SA 4.0'),
    'Fortress_of_Klis_06.jpg': ('Bernard Gagnon', 'CC BY-SA 4.0'),
    'Salona_-_amphitheatre_-_panorama.jpg': ('Pudelek (Marcin Szala)', 'CC BY-SA 3.0'),
    'Trogir-panorama-from-NW-mountain_2014-09-26.jpg': ('Reino Baptista', 'CC BY-SA 4.0'),
    'Panorama_of_Trogir.jpg': ('Mike Karavanov', 'CC BY 3.0'),
    'Marjana-Telegrin_hill_in_Split,_Croatia_(48693913857).jpg': ('dronepicr', 'CC BY 2.0'),
    'City_of_Split_Riva_panorama.jpg': ('Gordocro', 'Public domain'),
    'Cascada_de_Skradinski_Buk_(11).jpg': ('Alberto-g-rovi', 'CC BY 4.0'),
    'Cetina_(HR),_Quelle_"Blue_Eye"_und_Dinara_--_2022_--_0042.jpg': ('Anil Öztas', 'CC BY-SA 4.0'),
    'Rafting_Cetina_18.jpg': ('Cookies4ever', 'CC0'),
    'Omiš_Chorvátsko31.jpg': ('Ing. Mgr. Jozef Kotulič', 'CC BY-SA 4.0'),
    'Cevapi_in_Bosnia.jpg': ('Hibasi', 'CC BY-SA 4.0'),
}
