# -*- coding: utf-8 -*-
"""Innholdet til «Dette finnes i området» på de seks 10B-arkene.
Alle beløp er regnet om fra 2026-priser med 1 EUR = 10,77 kr (Norges Bank 14.9.2026) og rundet.
Hvert punkt er sjekket mot kilde 15.–16. september 2026; det som ikke er bekreftet, står det om i teksten."""

# (filnavn på Wikimedia Commons, bildetekst)
KRETA = dict(
    lede='Rethymno er en venetiansk havneby med en gamleby av smug, minareter og fontener, og en sammenhengende sandstrand som går 13 kilometer østover gjennom Platanes. '
         'Vestover ligger Chania med den venetianske havna en time unna, sørover krysser veien fjellene ned til Libyahavet, og innover i landet ligger klostre, juv og Kretas eneste ferskvannssjø. '
         'I juni er lufta 27–30 grader, sjøen 20–23, og det er nesten aldri regn. Livredderne er på plass fra 1. juni.',
    temaer=[
        dict(tittel='Strender gruppen faktisk kan dra til',
             lede='Hjemmestranda er rett utenfor døra. De store navnene på Kreta krever buss, og de beste av dem en hel dag — til gjengjeld er de verdt dagen.',
             bilder=[('Preveli Palm Beach 03.JPG', 'Preveli — palmeskogen møter Libyahavet'),
                     ('ELA - Long sandy beach at Elafonisi, Crete, Greece, 2015.jpg', 'Elafonisi, der sanden er rosa av knuste skjell'),
                     ('Balos 1.jpg', 'Balos-lagunen helt nordvest på øya'),
                     ('Damnoni Beach (1018849199).jpg', 'Damnoni ved Plakias'),
                     ('Falassarna - Kréta - panoramio (4).jpg', 'Falassarna, tre kilometer strand mot vest'),
                     ('Kreta - Kournas-See.jpg', 'Kournas — Kretas eneste ferskvannssjø')],
             punkter=[('Bystranda i Rethymno og Platanes',
                       'Tretten kilometer sammenhengende sand østover fra gamlebyen, gjennom Platanes og Adelianos Kampos. Solsenger, dusjer, strandbarer og livredningstårn hele veien. Karettskilpadden hekker på denne stranda, så det er skilt om hvor man ikke skal grave.',
                       'Rett utenfor hotellet · livreddere 1. juni–30. sept., 10–18'),
                      ('Preveli',
                       'En palmeskog følger elva Megas Potamos ned i en kløft og ut i Libyahavet. Man parkerer på toppen og går 20–30 minutter ned — og opp igjen i varmen etterpå. Nesten ingen fasiliteter: ta med vann.',
                       '38 km sør · 45–60 min kjøring'),
                      ('Damnoni',
                       'Grovkornet hvit sand i en lun bukt, vanligvis rolig og grunt. Vestsiden er organisert med parasoller, dusjer og snackbar. Østenden av bukta er nudiststrand — verdt å vite på forhånd når man kommer med en klasse.',
                       '35 km sør · fem km øst for Plakias'),
                      ('Elafonisi',
                       'Sanden er rosa av knuste skjell, og lagunen er bare rundt én meter dyp — man kan vade langt ut. Natura 2000-område: det er forbudt å ta med sand eller skjell hjem. Østsiden har parasoller, dusjer, livreddere og snackbarer.',
                       'Vest på øya · halvannen time fra Chania'),
                      ('Balos',
                       'Lagunen mellom fastlandet og Gramvousa, med tre farger vann i samme bilde. Med bil blir det åtte kilometer grusvei og deretter 850 trinn ned. Båten fra Kissamos slipper hele nedstigningen.',
                       '2 t 15 min fra Rethymno · båt eller 850 trinn'),
                      ('Falassarna',
                       'Tre kilometer strand vendt rett mot vest, fullt organisert med parasoller, vannsport og volleyball. Nordvestvinden gir ofte bølger. Tjue minutters gange unna ligger ruinene av den hellenistiske havna.',
                       'Vest for Kissamos · kjent for solnedgangen'),
                      ('Kournas-sjøen',
                       'Kretas eneste ferskvannssjø, mellom fjellene ovenfor Georgioupolis. De første ti–femten meterne er under én meter dype, midten er 22,5. Tråbåter og kajakk leies i strandkanten, og ferskvannsskilpaddene lar seg se.',
                       '25 min fra Rethymno · tråbåt ca. 110 kr timen'),
                      ('Georgioupolis — med forbehold',
                       'Over ti kilometer strand og et kapell ute på en steinmolo, men kysten har sterk strøm og det drukner folk her hvert år. Livreddere finnes bare på de mest besøkte partiene. Bading her bør bare skje når sjøen er rolig, og med voksne i vannkanten.',
                       '22 km · sterk strøm')]),
        dict(tittel='Historie de kan ta på',
             lede='Gratis inngang: det greske kulturdepartementet gir fri adgang til statlige arkeologiske steder og museer for elever og medfølgende lærere på skoletur fra EU- og EØS-land. Norge er EØS. Ta med deltakerliste og attest fra skolen — da koster Knossos null i stedet for 215 kroner per hode.',
             bilder=[('Kreta (GR), Amnatos, Kloster Arkadi -- 2023 -- 8553.jpg', 'Arkadi-klosteret, kretisk frihetssymbol'),
                     ('Knossos R03.jpg', 'Knossos — Europas eldste by'),
                     ('Bull leaping minoan fresco archmus Heraklion.jpg', 'Oksespranget, minoisk fresko i Heraklion'),
                     ('Kreta (GR), Rethymno, Fortezza -- 2023 -- 8236.jpg', 'Fortezza, Kretas største festning'),
                     ('Kreta (GR), Rethymno, Venezianischer Brunnen Rimondi -- 2023 -- 8762.jpg', 'Rimondi-fontenen fra 1626'),
                     ('Kreta (GR), Chania, Alter Hafen, Leuchtturm -- 2023 -- 8527.jpg', 'Fyret på den venetianske havna i Chania')],
             punkter=[('Knossos',
                       'Palasset fra rundt 1900 f.Kr. med tronsalen, søylene og gangsystemet som ble til myten om labyrinten og Minotauros. Åpent 08–20 i juni, siste innslipp 19:45.',
                       'Time fra Rethymno · 215 kr, gratis for skoleklasser fra EØS'),
                      ('Arkeologisk museum i Heraklion',
                       'Her henger freskene fra Knossos, blant dem oksespranget — ungdommer som kaster seg over ryggen på en okse, malt for 3 500 år siden. Originalene er her; det som står i Knossos er kopier.',
                       '215 kr · gratis for skoleklasser fra EØS'),
                      ('Arkadi-klosteret',
                       'Kretas nasjonalsymbol. I november 1866 søkte rundt tusen kretere tilflukt her under opprøret mot osmansk styre; etter to dagers kamp antente de kruttkammeret framfor å overgi seg. Kruttrommet og refektoriedøren med kulehull står der fremdeles, og kirkefasaden er fra 1587. Dekkede skuldre og knær.',
                       '23 km · 30–40 min · 32 kr'),
                      ('Fortezza i Rethymno',
                       'Venetianerne bygde festningen 1573–1580 etter at Uluç Ali brente byen. Rundt 1,3 kilometer murer gjør den til Kretas største. Inne står Sultan Ibrahim Han-moskeen der den venetianske katedralen lå. Billetten kjøpes i porten, ikke på nett.',
                       'I gangavstand · rundt 45–55 kr'),
                      ('Gamlebyen i Rethymno',
                       'Rimondi-fontenen fra 1626 med tre løvehoder, Neratze-moskeen som var venetiansk kirke før minareten kom, byporten Porta Guora og Loggiaen fra rundt 1625. Fyret på den venetianske havna er egyptisk, bygget på 1830-tallet.',
                       'Gratis · best i ettermiddagslyset'),
                      ('Den venetianske havna i Chania',
                       'Fyret ytterst på moloen ble reist av venetianerne rundt 1600 og bygget opp igjen av egypterne i 1839; det er 21 meter høyt og formet som en minaret. Firkas-festningen og Kretas sjøfartsmuseum ligger et par hundre meter unna.',
                       'En time vestover · fyret er gratis å se'),
                      ('Aptera',
                       'Antikk by rett ved motorveien mellom Chania og Rethymno, med romerske sisterner og utsikt over Souda-bukta. Lett å ta på veien til eller fra flyplassen.',
                       'Ved motorveien · 110 kr, gratis for skoleklasser fra EØS')]),
        dict(tittel='Dager der det skjer noe',
             lede='Kreta har både den harde varianten og den lette. Samaria er en av Europas lengste kløfter og en skikkelig prestasjon å gå; Imbros gir mye av det samme på en tredjedel av tida.',
             bilder=[('Gorge of Samaria Biosphere Reserve, Crete, Greece (2).jpg', 'Samaria-juvet, 16 kilometer nedover'),
                     ('Kreta (GR), Rethymno, Fortezza -- 2023 -- 8239.jpg', 'Festningsmurene over byen'),
                     ('Preveli Palm Beach Panorama 02.JPG', 'Kysten sørover mot Preveli')],
             punkter=[('Samaria-juvet',
                       'Seksten kilometer gjennom nasjonalparken, fem til sju timer, ulendt underlag hele veien og bare én retning: nedover og ut til havet ved Agia Roumeli, der ferga henter. Krever form og gode sko. Ingen slipper inn i hoveddelen etter rundt klokka 14.',
                       'Gratis for alle under 18 · sesongen åpner tidlig mai'),
                      ('Imbros-juvet',
                       'Det enkle alternativet: åtte kilometer, to og en halv til fire timer, nedoverbakke hele veien, og på det smaleste halvannen meter mellom veggene.',
                       '27 kr'),
                      ('Limnoupolis vannpark',
                       'Elleve sklier, et hovedbasseng på 1 500 kvadratmeter og en 206 meter lang «lazy river», sju kilometer utenfor Chania.',
                       '275 kr, ettermiddagsbillett rundt 185'),
                      ('Balos og Gramvousa med båt',
                       'Dagscruise fra Kissamos til piratøya Gramvousa med den venetianske festningen og skipsvraket, og videre til lagunen i Balos. Lavsesongpris gjelder til midten av juli.',
                       '430 kr voksen · bør forhåndsbestilles'),
                      ('Gokart i Varipetro',
                       'Ellevehundre meter bane fem kilometer fra Chanias gamleby. Karter fra 12 år og 145 cm, de større fra 14 år, og grupperace fra åtte personer.',
                       'Man–fre 12–23 · gratis henting i Chania-området'),
                      ('Agreco-gården',
                       'Gjenskapt tradisjonell kretisk gård rett øst for Rethymno, med dyr, gammelt håndverk og «bonde for en dag». Ligger i praksis i nabolaget til hotellet.',
                       'I Adele, ved siden av basen')]),
        dict(tittel='Kvelder, marked og mat',
             lede='Hva som faktisk skjer i uka 8.–15. juni 2027 er ikke publisert ennå — festivalprogrammene kommer først på nyåret. Dette er mønsteret slik det har vært.',
             bilder=[('Kreta (GR), Rethymno, Alter Hafen, Leuchtturm -- 2023 -- 8328.jpg', 'Den gamle havna i Rethymno'),
                     ('Harbor, Venetian shipyards and Lighthouse in Chania. Crete, Greece.jpg', 'Kvelden ved havna i Chania'),
                     ('Gyro 03.jpg', 'Gyros i pita — standardlunsjen'),
                     ('Bougatsa (with vannila custard) - IL.FOXO 2026-02-13.jpg', 'Bougatsa, frokostbakverket')],
             punkter=[('Folkloreopptoget i Chania',
                       'Paradosiaki Strata: over 1 500 dansere og musikere fra tjue foreninger går i opptog langs den venetianske havna hver tirsdag kveld gjennom sommeren, gratis å se på. I 2026 startet rekka 16. juni — altså like etter denne uka. Verdt å spørre Chania kommune om startdatoen for 2027.',
                       'Tirsdager 20:00 · gratis · usikker startdato'),
                      ('Renaissance-festivalen i Rethymno',
                       'Byens store festival med konserter og teater på Fortezza. Den ligger normalt i juli–september, så regn ikke med den i juni.',
                       'Normalt juli–september'),
                      ('Markedsdager',
                       'Laiki agora, det store gatemarkedet, går torsdag morgen ved Kommunehagen og lørdag morgen ved bussstasjonen, til rundt klokka 14. Begge faller innenfor uka.',
                       'Torsdag 10. og lørdag 12. juni'),
                      ('Kvelden i gamlebyen',
                       'Palmealléen Eleftheriou Venizelou går langs sjøen mot marinaen, og det er der folk samler seg når sola går ned. Butikkene holder åpent til 21, suvenirbutikkene lenger.',
                       'Gangavstand fra Rethymno-hotellet'),
                      ('Hva mat koster',
                       'Gyros i pita er standardlunsjen og kan koste opp mot 70 kroner på de mest turistiske stedene — Kreta er dyrest i Hellas på akkurat dette. Bougatsa, filodeig med ost eller vaniljekrem, er frokosten.',
                       'Gyros opp mot 70 kr')]),
    ])

COSTABLANCA = dict(
    lede='Albir ligger i en bukt mellom Altea og Benidorm, med fjellryggen Serra Gelada rett i ryggen og et fyr ytterst på neset. '
         'Stranda har blått flagg, promenaden har restauranter og en stjernerekke fra filmfestivalen, og tjue minutter unna med lokalbuss ligger Benidorm med flere fornøyelses- og vannparker. '
         'Innover i landet ligger fjellandsbyen Guadalest og fossene i Algar, og livredningssesongen starter 1. juni — like før gruppen lander.',
    temaer=[
        dict(tittel='Bading, fra rullestein til finsand',
             lede='Albirstranda er rullestein og klart vann, som er ideelt for snorkling og mindre ideelt for barbeint fotball. Vil de ha finsand og folkeliv, er Benidorm en kort busstur unna.',
             bilder=[('Bosque de Sierra Helada con vistas..jpg', 'Serra Gelada over bukta ved Albir'),
                     ('Playa de Levante, Benidorm, España, 2014-07-02, DD 86.JPG', 'Playa de Levante i Benidorm'),
                     ('Isla de Benidorm, España, 2014-07-02, DD 58.JPG', 'Isla de Benidorm, i naturparken'),
                     ('Des de la Serra Gelada cap a la mar - panoramio.jpg', 'Klippene i Serra Gelada faller rett i havet'),
                     ('Playa de Levante, Benidorm, España, 2014-07-02, DD 33.JPG', 'Strandliv i Benidorm'),
                     ('Playa de l\'Albir.JPG', 'Albirstranda — rullestein og klart vann')],
             punkter=[('Albirstranda',
                       'Rullestein og svært klart vann, som gjør den til en av de bedre snorklestrendene på kysten. Dusjer, toaletter, solsengutleie, rullestolramper og livreddere i sesong. Stranda fikk blått flagg både i 2025 og 2026.',
                       'Rett utenfor døra'),
                      ('Playa de Levante i Benidorm',
                       'To kilometer finsand med promenade, strandbarer og strandbibliotek som er åpent 11–16. Blått flagg i 2026. Livredderne er på jobb 10–19 i juni; ni av dem holder til på denne stranda alene.',
                       '20 min med lokalbuss'),
                      ('Cala del Tio Ximo og Cala Almadrava',
                       'To små grus- og rullesteinsbukter på nordsiden av Benidorm, begge kjent for snorkling og begge med egen livredder i sesongen. Nås til fots eller med sykkel fra byen.',
                       'Små, og derfor tidlig fulle'),
                      ('Cala de Finestrat',
                       'Finsand i en lukket bukt med svært lett adkomst, restauranter og kafeer rundt hele. Det roligste alternativet til Levante.',
                       'Sør for Benidorm'),
                      ('Strendene i Altea',
                       'Cap Blanch, El Bol, La Roda og L\'Espigó har alle blått flagg i 2026. Altea er den stille naboen: rullestein, seilbåter og en gamleby rett bak.',
                       'Nabobyen nordover'),
                      ('Isla de Benidorm',
                       'Øya utenfor ligger i naturparken Serra Gelada, med store posidonia-enger og klipper på over 300 meter — snorkling i et vernet område. Båten går fra havna i Benidorm fra klokka 10, omtrent hver femtiende minutt, og minst to timer må settes av. Noen av båtene har glassbunn.',
                       '235 kr voksen, 150 kr barn')]),
        dict(tittel='Historie rett i nærområdet',
             lede='Man trenger ikke reise langt: en romersk villa ligger i Albir, et vakttårn fra pirattiden står oppe ved fyret, og fjellandsbyen Guadalest er en av de mest fotograferte i Spania.',
             bilder=[('Guadalest, Alicante, España, 2023-01-21, DD 11.jpg', 'Guadalest, landsbyen på fjellknausen'),
                     ('Castillo, Guadalest, Alicante, España, 2023-01-21, DD 27.jpg', 'Borgen i Guadalest'),
                     ('Cúpula d\'Altea.jpg', 'Den blå kuppelen i Altea'),
                     ('Vista de Alicante, España, 2014-07-04, DD 67-70 PAN.JPG', 'Santa Bárbara-borgen over Alicante'),
                     ('Faro de Punta Albir 03.jpg', 'Neset med fyret ytterst i Albir'),
                     ('Colorful buildings of the historical La Vila Joiosa, Alicante, Spain, 2022 January.jpg', 'De malte husene i Villajoyosa')],
             punkter=[('Villa Romana de l\'Albir',
                       'Romersk villa gravd fram midt i Albir og gjort om til friluftsmuseum. Gratis inngang, og fra juni holder det sommeråpent tirsdag til lørdag, formiddag og kveld.',
                       'Gratis · i gangavstand'),
                      ('Turen til fyret',
                       'Fem kilometer tur-retur på asfaltert vei, rundt hundre høydemeter og halvannen time i rolig tempo. Underveis passerer man okergruvene fra 1800-tallet og grotta Cova del Bou, og fra utsiktspunktene ser man Alteabukta, Serra de Bèrnia og Peñón de Ifach — i klarvær helt til Ibiza. Tolkningssenteret i fyret er gratis.',
                       'Gratis · 1–1,5 time · «Sendero Azul»'),
                      ('Torre Bombarda',
                       'Vakttårnet oppe ved fyret er nevnt i en rapport fra 1563 og var en del av Felipe IIs varslingskjede mot berberpirater. I dag står bare det sekskantede fundamentet og nesten to meter tykke murrester igjen.',
                       '111 moh. · på veien til fyret'),
                      ('Altea gamleby',
                       'Kirken Nuestra Señora del Consuelo ble bygget mellom 1901 og 1910, og kuppelen i blå og hvite fliser har fått kallenavnet «Middelhavets kuppel». Rundt den ligger brolagte smug og hvitkalkede hus oppover haugen.',
                       'Nabobyen · lokalbuss'),
                      ('Guadalest',
                       'Landsbyen ligger på en fjellknaus med borgen på toppen, og adkomsten går gjennom en tunnel hugget i fjellet. Nedenfor ligger demningen med turkist vann. Et av de mest besøkte stedene i provinsen — dra tidlig.',
                       'Innover i fjellene'),
                      ('Santa Bárbara-borgen i Alicante',
                       'Borgen ligger 166 meter over byen med utsikt over hele havna og bystranda. Selve anlegget er gratis; heisen opp fra stranda koster rundt 30 kroner. Åpent 10–20 fram til 16. juni, altså hele uka deres.',
                       'Gratis · heis ca. 30 kr'),
                      ('Villajoyosa og sjokolademuseet',
                       'Fiskerbyen med de sterkt malte husene langs elva. Valor-fabrikken har gratis omvisning med smaksprøver, 45–60 minutter, på spansk og engelsk — men grupper på 15 eller flere må bestille på forhånd, og de tar maks 50 om gangen.',
                       'Gratis omvisning · må bestilles')]),
        dict(tittel='Parker, fosser og grotter',
             lede='Dette er den delen av Spania som har flest fornøyelsesparker på ett sted. Terra Mítica gir gruppepris fra tjue betalende, og det utgjør en god del når det er 28 som skal inn.',
             bilder=[('Aigua i roca del toll Blau de les fonts de l\'Algar.jpg', 'Algar — turkise kulper i elva'),
                     ('El toll del Baladre de les fonts de l\'Algar.jpg', 'Fossene i Algar'),
                     ('La grotte de canelobre - panoramio (6).jpg', 'Canelobre-grotta, 70 meter under hvelvet'),
                     ('Tabarca Island-Alicante (Spain) - 48502234451.jpg', 'Tabarca, øya utenfor Alicante'),
                     ('Magnus_Colossus_tematización.JPG', 'Terra Mítica i Benidorm')],
             punkter=[('Terra Mítica',
                       'Fornøyelsespark bygget rundt Middelhavets gamle kulturer, med parkens store berg-og-dal-baner. Sesongen går fra midten av mai til begynnelsen av november, og porten åpner 10:30. Gruppepris krever minst tjue betalende og forhåndsbestilling.',
                       'Gruppepris fra 325 kr voksen, 270 kr junior'),
                      ('Aqualandia',
                       'Vannparken i Benidorm.',
                       '440 kr voksen, 355 kr for 4–12 år'),
                      ('Terra Natura og Aqua Natura',
                       'Dyrepark og vannpark side om side. Vannparken er åpen daglig fra slutten av mars til begynnelsen av november, så den er i drift i juni.',
                       '355 kr · kombibillett 505 kr'),
                      ('Les Fonts de l\'Algar',
                       'Elva faller gjennom en rekke kulper med turkist vann, og sju av dem er tilrettelagt for bading. Rundløypa er halvannen kilometer og tar tre kvarter. Studentrabatt på tjue prosent, og livredder i påske- og sommersesongen.',
                       'Rundt 54 kr · 43 kr med studentbevis'),
                      ('Cuevas del Canelobre',
                       'Grotta ligger 700 meter over havet i fjellet ved Busot, og hvelvet inne er 70 meter høyt — et av de høyeste i Spania. Grupper på tjue eller flere får halv pris.',
                       'Gruppepris rundt 50 kr'),
                      ('Kajakk fra Albirstranda',
                       'Guidet kajakktur langs klippene i Serra Gelada til Cala de la Mina, to og en halv time, med snorkleutstyr inkludert. Går daglig klokka 16, men bare ti plasser per tur — for 28 må det deles opp eller avtales særskilt.',
                       '485 kr per person · maks 10 per tur'),
                      ('Tabarca',
                       'Liten, flat øy med festningsmur og klart vann, med strand, snorklebukter og restauranter. Båten fra Alicante bruker tre kvarter til en time, og returbilletten er åpen.',
                       'Båt fra Alicante · 45–60 min')]),
        dict(tittel='Uka, markedet og maten',
             lede='2027-programmene er ikke publisert. Det som er verdt å merke seg er at Alicantes store bålfest, Hogueras de San Juan, går 20.–24. juni — altså etter at gruppen har reist hjem.',
             bilder=[('Absis i cúpula, església de la mare de Déu del Consol d\'Altea.JPG', 'Altea om ettermiddagen'),
                     ('Altea, Spain (26889065385).jpg', 'Promenaden i Altea'),
                     ('Playa del Racó del Albir.JPG', 'Racó del Albir')],
             punkter=[('Søndagsmarkedet i Albir',
                       'Hver søndag fra 07:30 til 14:00, med rundt 175 boder: tretti med frukt og grønt og resten tekstil og gaver. Helsemyndighetene i regionen har kåret det til et av de best drevne markedene i Valencia-regionen. Søndag 13. juni faller midt i uka.',
                       'Søndag 13. juni · i gangavstand'),
                      ('Hogueras de San Juan',
                       'Alicantes største fest, med bålfigurer i gatene og mascletà på Plaza de los Luceros. Den går 20.–24. juni hvert år og avsluttes med at figurene brennes natt til 25. — helt utenfor denne uka. Det samme gjelder sankthansbålene 23.–24. juni, som kommunen dessuten har forbudt på Albirstranda.',
                       'Etter hjemreise'),
                      ('Filmfestivalen i l\'Alfàs del Pi',
                       'Går i juli, ikke i juni. Men stjernene i fortauet langs Albir-promenaden — Paseo de las Estrellas — ligger der hele året.',
                       'Promenaden er der uansett'),
                      ('Norsk i Albir',
                       'Det finnes en norsk skole i Albir med trinn 1–10, og Sjømannskirken Albir-Villajoyosa ligger i Carrer Mart rett ved stranda, med kafé og vafler, åpent tirsdag til fredag 10–14 og lørdag 11–14. Greit å vite om noe skulle skje.',
                       'Sjømannskirken: tirs–fre 10–14'),
                      ('Hva mat koster',
                       'Dagens meny med drikke og brød ligger i snitt rundt 140 kroner i Valencia-regionen. Det er det billigste varme måltidet man får kjøpt.',
                       'Menú del día ca. 140 kr')]),
    ])

SPLIT = dict(
    lede='Split er bygget inne i et romersk palass. Diokletian reiste det rundt år 300, og etter at Salona falt flyttet folk inn mellom murene og ble aldri borte — i dag er palassgatene fulle av kafeer, butikker og leiligheter, og det koster ingenting å gå der. '
         'Rett utenfor ligger Bačvice, en sandbukt så grunn at byen har funnet opp sin egen ballek i vannkanten. Bak byen reiser fjellene seg med festningen i Klis, og langs kysten og ut mot øyene ligger fossefall, kløfter og strender.',
    temaer=[
        dict(tittel='Bading, og en ballek byen fant opp selv',
             lede='Split har byens egne strender i gangavstand, og de store, kjente lenger ute langs kysten. Nesten alt er rullestein — badesko er en billig investering.',
             bilder=[('Bacvice Beach in Split, Croatia (48608741537).jpg', 'Bačvice, bysanden midt i Split'),
                     ('Picigolwiki.jpg', 'Picigin — spillet som ble til på Bačvice i 1908'),
                     ('J32 653 Bol, Zlatni Rat, Hvar.jpg', 'Zlatni Rat på Brač'),
                     ('Kasjuni Beach - Split - Croatia 2023 05.jpg', 'Kašjuni under Marjan'),
                     ('Brela BW 2024-10-04 15-43-18.jpg', 'Brela, under Biokovo-fjellet'),
                     ('Podstrana Split 20210710 090931.jpg', 'Kysten i Podstrana')],
             punkter=[('Bačvice',
                       'Sandstrand med så grunt vann at man kan gå hundre meter ut, fem–ti minutter fra palasset. Livreddere om sommeren, dusjer, kafeer og pizzeria. Den tar rundt tusen mennesker og blir full.',
                       '5–10 min fra gamlebyen · åpen 09–21'),
                      ('Picigin',
                       'Byens eget spill, oppstått nettopp på Bačvice i 1908 da studenter tok det med hjem fra Praha. Det spilles i ankeldypt vann med en avskrelt tennisball, ballen slås med flat hånd og skal aldri treffe vannet. Det finnes ingen poeng — man taper ikke, man redder ballen. Det arrangeres VM i picigin på denne stranda hvert år, og det dømmes på stil.',
                       'Gratis · alt som trengs er en tennisball'),
                      ('Kašjuni',
                       'Rullesteinsstrand under Marjan-skogen med turkist vann og få trær nede ved vannet; det er stranda folk drar til for solnedgangen. Buss 12 fra byen.',
                       '3 km · buss 12 · ta med badesko'),
                      ('Žnjan',
                       'Splits største strand, to kilometer lang, ferdig totalrenovert i 2025. Den har nå livreddere, dusjer, turistlegekontor i sesongen og en sportssone med gratis baner for volleyball, basket, tennis og burfotball, pluss skatepark. Førstemann til mølla, ingen booking.',
                       'Buss 8 eller 15 · banene er gratis'),
                      ('Strendene i Podstrana',
                       'Seks kilometer kystlinje med badeplasser nesten hele veien. Strožanac er rullestein med dusjer, restaurant og utleie av parasoller. For gruppen som bor her er dette hjemmestranda.',
                       'Hjemmestranda for «best»-alternativet'),
                      ('Omiš — Velika Plaža',
                       'Sjuhundre meter ekte sand med blått flagg, grunt hundre–to hundre meter ut, dusjer, garderober, livreddere og akvapark. Elva Cetina munner ut i enden, så vannet er merkbart kaldere der.',
                       '25 km · buss 60, ca. 45 min, hver halvtime'),
                      ('Brela',
                       'Fire hundre meter rullestein i furuskog under Biokovo-fjellet, med «Brela-steinen» stående rett utenfor og sju kilometer strandpromenade videre.',
                       'Knapt en time med buss'),
                      ('Zlatni Rat på Brač',
                       'Rullesteinstanga som skifter form med strømmen — Kroatias mest fotograferte strand. Sesongkatamaranen går direkte fra Split til Bol på under halvannen time; alternativet er bilferge til Supetar, 50 minutter, og buss videre.',
                       'Bilferge 70 kr voksen, 34 kr barn')]),
        dict(tittel='En by som er et romersk palass',
             lede='UNESCO skrev inn «Det historiske Split med Diokletians palass» i 1979. Det spesielle er at det ikke er et museum: folk bor der, og portene, Peristylet og Vestibylen er åpne hele døgnet og koster ingenting.',
             bilder=[('Aerial_view_of_Diocletian\'s_Palace_in_Split,_Croatia_(48608247353).jpg', 'Palasset sett ovenfra — byen inni murene'),
                     ('Peristyle_of_Diocletian\'s_Palace,_Split_(11908116224).jpg', 'Peristylet midt i palasset'),
                     ('Bell Tower Of Cathedral of Saint Domnius - Split.jpg', 'Klokketårnet, 57 meter'),
                     ('Fortress of Klis 06.jpg', 'Klis-festningen i fjellpasset'),
                     ('Salona - amphitheatre - panorama.jpg', 'Amfiteateret i Salona'),
                     ('Trogir-panorama-from-NW-mountain 2014-09-26.jpg', 'Trogir, UNESCO-by på en egen øy')],
             punkter=[('Diokletians palass',
                       'Reist rundt år 300 som keiserens pensjonistbolig, og i dag selve bykjernen. Gatene, de fire portene, Peristylet og den hvelvede Vestibylen er gratis og alltid åpne. Kjellerne under palasset, som holdt bygget oppe og i dag er utstillingsrom, koster inngang.',
                       'Gratis · kjellerne rundt 65 kr'),
                      ('Katedralen sv. Duje',
                       'Bygget som Diokletians mausoleum rundt år 305 og innviet som kirke på 600-tallet — trolig den eldste katolske katedralen i verden som fremdeles brukes i sin opprinnelige bygning. Klokketårnet ved siden av er 57 meter og kan bestiges. Ironien er at mausoleet til keiseren som forfulgte de kristne, ble en kirke viet en av hans egne martyrer.',
                       'Katedral 55 kr · tårn 75 kr · kombi 130 kr'),
                      ('Klis-festningen',
                       'Festningen ligger i fjellpasset ni kilometer nord for byen og kontrollerte veien inn til Dalmatia. Petar Kružić holdt den mot osmanerne i 25 år før den falt i 1537. I Game of Thrones er den byen Meereen. Buss 22 tar en snau halvtime.',
                       'Buss 22 · 75 kr voksen, 40 kr barn'),
                      ('Salona',
                       'Romerbyen som Split vokste ut av, med et amfiteater som tok opptil 17 000 tilskuere, bymur med nitti tårn, bad og nekropolen Manastirine. På sitt største bodde det kanskje 60 000 mennesker her. Billetten gjelder også Arkeologisk museum inne i Split.',
                       'Buss 1, 15–20 min · 43 kr voksen, 22 kr barn'),
                      ('Trogir',
                       'UNESCO-by fra 1997 på en egen liten øy mellom fastlandet og Čiovo, med Radovans portal på katedralen og Kamerlengo-festningen ytterst. Lokalbuss 37 bruker rundt en time.',
                       '27 km vest · buss 37'),
                      ('Marjan',
                       'Byfjellet er en furuskog rett vest for gamlebyen, gratis og alltid åpent. Første utsiktspunkt tar et kvarter, toppen Telegrin på 178 meter tar tre kvarter fra Rivaen. På veien ligger kapellene sv. Nikola fra 1200-tallet og sv. Jere fra 1400-tallet, med eremitthuler hugget i klippen over.',
                       'Gratis · 45–60 min til toppen')]),
        dict(tittel='Dager i fart',
             lede='Dette er den delen av programmet elever pleier å huske: rafting nedover Cetina, zipline over kløfta, og fosser man faktisk får bade ved — men bare de riktige stedene.',
             bilder=[('Cascada de Skradinski Buk (11).jpg', 'Skradinski buk i Krka nasjonalpark'),
                     ('Rafting Cetina 18.jpg', 'Rafting på Cetina'),
                     ('Cetina (HR), Quelle "Blue Eye" und Dinara -- 2022 -- 0042.jpg', 'Cetinas kilde, «det blå øyet»'),
                     ('Omiš Chorvátsko31.jpg', 'Is i Omiš etter rafting'),
                     ('Marjana-Telegrin hill in Split, Croatia (48693913857).jpg', 'Marjan, byfjellet med kajakkvannet under')],
             punkter=[('Krka nasjonalpark',
                       'Fossefallene ved Skradinski buk faller trinn for trinn gjennom en kalksteinkløft. Merk: bading er bare tillatt på merkede steder ved Roški slap, Stinice og Pisak, fra 1. juni til 30. september, og på eget ansvar — man bader ikke lenger ved selve Skradinski buk. Organisert gruppe fra tjue personer får egen pris.',
                       'Gruppepris 325 kr voksen, 160 kr for 7–18 år'),
                      ('Rafting på Cetina',
                       'Tolv kilometer nedover elva gjennom kløfta, tre–fire timer på vannet og seks–sju timer totalt med transport. Strykene er klasse II–III, altså moderate, og minstealderen er åtte år. Henting på Rivaen.',
                       '380–650 kr · fra 8 år'),
                      ('Zipline i Omiš',
                       'Åtte liner på til sammen 2 100 meter over Cetina-kløfta, den lengste 700 meter, på det høyeste 150 meter over bakken. To og en halv til tre timer. Fra sju år, maks 140 kilo, og grupper kjøres i puljer — bestill minst et døgn før.',
                       'Rundt 860 kr · puljevis for 28'),
                      ('Havkajakk under Marjan',
                       'Ti kilometer langs klippene på undersiden av byfjellet, tre–fire timer, snorkleutstyr med i prisen og klippehopping for dem som vil. Fra åtte år sammen med voksen.',
                       'Rundt 540 kr · fra 8 år'),
                      ('Biokovo Skywalk',
                       'Glassplattform som stikker ut fra fjellsiden 1 228 meter over Makarska. Adgangen er begrenset til rundt tjue kjøretøy i timen, så dette må forhåndsbestilles.',
                       '160 kr · må bestilles'),
                      ('Blå grotte og Hvar',
                       'Elleve timers hurtigbåttur til grotta på Biševo og videre innom Hvar. Grotteavgiften betales kontant i tillegg og er lavere før 20. juni.',
                       'Grotteavgift ca. 130 kr i juni')]),
        dict(tittel='Byen om kvelden, markedet og maten',
             lede='2027-programmene er ikke publisert. Det som er verdt å vite er at de to store — Splitsko ljeto fra midten av juli og Ultra Europe i juli, som uansett er 18-årsgrense — begge ligger etter denne uka. Til gjengjeld er byen langt roligere i begynnelsen av juni.',
             bilder=[('City of Split Riva panorama.jpg', 'Rivaen, byens stue'),
                     ('Panorama of Trogir.jpg', 'Kvelden langs vannet'),
                     ('Cevapi in Bosnia.jpg', 'Ćevapi — den billige mettende middagen'),
                     ('Split Cathedral Bell Tower From The Vestibule - Split.jpg', 'Vestibylen, der gatemusikerne synger')],
             punkter=[('Middelhavets filmfestival',
                       'Mediterranean Film Festival Split viste over hundre filmer i 2026 og gikk 11.–20. juni — altså midt i den uka gruppen ville vært der. Friluftskinoen på Bačvice tar 700 mennesker. Datoene for 2027 er ikke satt, men festivalen har ligget i midten av juni.',
                       'Traff 11.–20. juni i 2026'),
                      ('Pazar og fisketorget',
                       'Grønnsakstorget ligger rett utenfor palassets østmur og er åpent daglig 06–14 med rundt seksti selgere; kom før klokka ni. Fisketorget i Kraj Sv. Marije har vært i drift siden 1890, er åpent mandag til lørdag 07–13, og tar kontanter.',
                       'Daglig · frukt til lunsj for en femtilapp'),
                      ('Rivaen',
                       'Promenaden langs sjøen foran palassmuren er byens stue: palmer, kafeer og folk som går fram og tilbake til langt på kveld. Det er også herfra båtturene og raftingbussene henter.',
                       'Rett utenfor palasset'),
                      ('Kvelden — verdt å planlegge',
                       'Barene inne i palassgatene holder åpent til rundt ett. De virkelig høylytte stedene ligger utenfor gamlebyen og nede på Bačvice, som er strand om dagen og nattklubb etter mørkets frembrudd. Legg kveldsprogrammet i gamlebyen, ikke på Bačvice.',
                       'Gamlebyen om kvelden, ikke Bačvice'),
                      ('Hva mat koster',
                       'Burek koster 16–27 kroner, ćevapi med lefse 43–65, og en hel vedfyrt pizza 75–97. En kaffe koster halvparten så mye ti meter fra Rivaen som på den.',
                       'Ćevapi 43–65 kr')]),
    ])

OMRAADE = {'Kreta': KRETA, 'Costa Blanca': COSTABLANCA, 'Split': SPLIT}
